from django.urls import path
from . import views

urlpatterns = [
    path("ledger-groups/", views.ledger_groups_list, name="ledger-groups-list"),
    path("ledger-groups/create/", views.ledger_group_create, name="ledger-group-create"),
    path("ledgers/create/", views.ledger_create, name="ledger-create"),
    path("ledgers/name-available/", views.ledger_name_available, name="ledger-name-available"),
    path("ledgers/agent-id-available/", views.ledger_agent_id_available, name="ledger-agent-id-available"),
    path("ledgers/<int:ledger_id>/", views.ledger_detail, name="ledger-detail"),
    path("ledgers/<int:ledger_id>/update/", views.ledger_update, name="ledger-update"),
    path("ledgers/<int:ledger_id>/delete/", views.ledger_delete, name="ledger-delete"),
    path("customers/", views.customers_list, name="customers-list"),
    path("suppliers/", views.suppliers_list, name="suppliers-list"),
    path("accounts/", views.accounts_list, name="accounts-list"),
    path("ledger-book/", views.ledger_book_report, name="ledger-book-report"),
    path("day-book/", views.day_book_report, name="day-book-report"),
    path("cash-bank-book/", views.cash_bank_book_report, name="cash-bank-book-report"),
    path("tickets/", views.tickets_list, name="tickets-list"),
    path("tickets/create/", views.ticket_create, name="ticket-create"),
    path("tickets/<int:ticket_id>/update/", views.ticket_update, name="ticket-update"),
    path("tickets/<int:ticket_id>/", views.ticket_detail, name="ticket-detail"),
    path("tickets/<int:ticket_id>/jv-preview/", views.ticket_jv_preview, name="ticket-jv-preview"),
    path("tickets/jv-preview-draft/", views.ticket_jv_preview_draft, name="ticket-jv-preview-draft"),
    path("vouchers/", views.vouchers_list, name="vouchers-list"),
    path("vouchers/create/", views.voucher_create, name="voucher-create"),
    path("vouchers/<int:voucher_id>/", views.voucher_detail, name="voucher-detail"),
    path("vouchers/<int:voucher_id>/update/", views.voucher_update, name="voucher-update"),
    path("supplier-commission-rules/", views.supplier_commission_rules_list, name="supplier-commission-rules-list"),
    path("supplier-commission-rules/create/", views.supplier_commission_rule_create, name="supplier-commission-rule-create"),
    path("supplier-commission-rules/<int:rule_id>/delete/", views.supplier_commission_rule_delete, name="supplier-commission-rule-delete"),
    path("ledgers-by-group/", views.ledgers_by_group_name, name="ledgers-by-group"),
    path("master-mapping/", views.master_mapping_list, name="master-mapping-list"),
    path("master-mapping/save/", views.master_mapping_save, name="master-mapping-save"),
    path("master-mapping/<int:mapping_id>/delete/", views.master_mapping_delete, name="master-mapping-delete"),
    path("fop-master/", views.fop_master_list, name="fop-master-list"),
    path("fop-master/save/", views.fop_master_save, name="fop-master-save"),
    path("fop-master/<int:card_id>/delete/", views.fop_master_delete, name="fop-master-delete"),
    path("pg-master/", views.pg_master_list, name="pg-master-list"),
    path("pg-master/save/", views.pg_master_save, name="pg-master-save"),
    path("pg-master/<int:gateway_id>/delete/", views.pg_master_delete, name="pg-master-delete"),
    path("company-master/", views.company_master_list, name="company-master-list"),
    path("company-master/save/", views.company_master_save, name="company-master-save"),
    path("company-master/<int:company_id>/delete/", views.company_master_delete, name="company-master-delete"),
]