# Generated by Django 5.0.6 on 2026-09-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_ticketline_supplier_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketline',
            name='fop',
            field=models.CharField(blank=True, choices=[('Own Card', 'Own Card'), ('Client Card', 'Client Card'), ('Cash', 'Cash')], max_length=20, null=True),
        ),
    ]
