# Generated by Django 5.0.6 on 2026-09-16 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_ticketline_multi_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketline',
            name='ssr_markup',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='ticketline',
            name='ssr_service_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
