# Generated by Django 5.0.6 on 2026-09-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_ticketline_ssr_markup_ticketline_ssr_service_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierCommissionRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField()),
                ('rule_type', models.CharField(default='Commission', max_length=20)),
                ('office_id', models.CharField(max_length=30)),
                ('supplier_name', models.CharField(blank=True, max_length=200, null=True)),
                ('travel_type', models.CharField(blank=True, max_length=20, null=True)),
                ('airline_category', models.CharField(blank=True, max_length=10, null=True)),
                ('cabin', models.CharField(blank=True, max_length=30, null=True)),
                ('fare_type', models.CharField(blank=True, max_length=60, null=True)),
                ('calc_type', models.CharField(blank=True, choices=[('Percentage', 'Percentage'), ('Flat', 'Flat')], max_length=12, null=True)),
                ('calc_pct', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('flat_amt', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valid_upto', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'SupplierCommissionRules',
                'indexes': [models.Index(fields=['company_id', 'office_id'], name='SupplierCom_company_846f4d_idx')],
            },
        ),
    ]
