# Generated by Django 5.0.6 on 2026-09-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_suppliercommissionrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliercommissionrule',
            name='comm_on',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
