# Generated by Django 5.0.6 on 2026-09-17 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_suppliercommissionrule_comm_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField()),
                ('product_type', models.CharField(choices=[('Airline', 'Airline'), ('Hotel', 'Hotel'), ('Bus', 'Bus'), ('Visa', 'Visa'), ('Insurance', 'Insurance'), ('Rail', 'Rail')], max_length=20)),
                ('masters_category', models.CharField(choices=[('Earnings From Customer', 'Earnings From Customer'), ('Earnings From Supplier', 'Earnings From Supplier'), ('Expenditure To Customer', 'Expenditure To Customer'), ('GST and TDS', 'GST and TDS')], max_length=40)),
                ('field_name', models.CharField(max_length=60)),
                ('ledger_name', models.CharField(blank=True, max_length=200, null=True)),
                ('effective_from', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ledger', models.ForeignKey(db_column='ledger_id', on_delete=django.db.models.deletion.PROTECT, related_name='master_mappings', to='accounting.ledger')),
            ],
            options={
                'db_table': 'MasterMapping',
                'indexes': [models.Index(fields=['company_id', 'product_type', 'masters_category'], name='MasterMappi_company_4a09ab_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='mastermapping',
            constraint=models.UniqueConstraint(fields=('company_id', 'product_type', 'field_name'), name='uq_master_mapping_field'),
        ),
    ]
