# Generated by Django 5.0.6 on 2026-09-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_mastermapping_mastermapping_uq_master_mapping_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastermapping',
            name='masters_category_id',
            field=models.SmallIntegerField(default=1),
        ),
    ]
