# Generated by Django 5.0.6 on 2026-09-17 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_mastermapping_masters_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FOPMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField()),
                ('card_type', models.CharField(choices=[('Own Card', 'Own Card'), ('Client Card', 'Client Card')], max_length=20)),
                ('card_number', models.CharField(max_length=40)),
                ('card_master_ledger_name', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_master_ledger', models.ForeignKey(db_column='card_master_ledger_id', on_delete=django.db.models.deletion.PROTECT, related_name='fop_master_rows', to='accounting.ledger')),
            ],
            options={
                'db_table': 'FOPMaster',
                'indexes': [models.Index(fields=['company_id', 'card_type'], name='FOPMaster_company_632257_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='fopmaster',
            constraint=models.UniqueConstraint(fields=('company_id', 'card_number'), name='uq_fop_master_card_number'),
        ),
    ]
