# Generated by Django 5.0.6 on 2026-09-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_fopmaster_fopmaster_uq_fop_master_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketline',
            name='card_number',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
