# Generated by Django 5.0.6 on 2026-09-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_ticketline_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='payment_gateway_ref',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
