# Generated by Django 5.0.6 on 2026-09-17 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_ticket_payment_gateway_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='PGMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField()),
                ('gateway_name', models.CharField(max_length=100)),
                ('payment_master_ledger_name', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_master_ledger', models.ForeignKey(db_column='payment_master_ledger_id', on_delete=django.db.models.deletion.PROTECT, related_name='pg_master_rows', to='accounting.ledger')),
            ],
            options={
                'db_table': 'PGMaster',
                'indexes': [models.Index(fields=['company_id'], name='PGMaster_company_7eed62_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='pgmaster',
            constraint=models.UniqueConstraint(fields=('company_id', 'gateway_name'), name='uq_pg_master_gateway_name'),
        ),
    ]
