# Generated by Django 5.0.6 on 2026-09-18 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0018_pgmaster_pgmaster_uq_pg_master_gateway_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketline',
            name='supp_addl_markup',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='ticketline',
            name='supp_addl_service_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='ticketline',
            name='supp_gst_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='ticketline',
            name='supp_markup',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='ticketline',
            name='supp_service_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
