# Generated by Django 5.0.6 on 2026-09-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_ticketline_supp_addl_markup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastermapping',
            name='masters_category',
            field=models.CharField(choices=[('Earnings From Customer', 'Earnings From Customer'), ('Earnings From Supplier', 'Earnings From Supplier'), ('Expenditure To Customer', 'Expenditure To Customer'), ('Expenditure To Supplier', 'Expenditure To Supplier'), ('GST and TDS', 'GST and TDS')], max_length=40),
        ),
    ]
