# Generated by Django 5.0.6 on 2026-09-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_alter_mastermapping_masters_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='fopmaster',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
