# Generated by Django 5.0.6 on 2026-09-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0021_fopmaster_bank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketline',
            name='airline_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ticketline',
            name='airline_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
