# Generated by Django 5.0.6 on 2026-09-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0022_alter_ticketline_airline_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketline',
            name='passenger_name',
            field=models.CharField(max_length=50),
        ),
    ]
