# Generated by Django 5.0.6 on 2026-09-21 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0023_alter_ticketline_passenger_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fopmaster',
            name='card_master_ledger',
            field=models.ForeignKey(blank=True, db_column='card_master_ledger_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fop_master_rows', to='accounting.ledger'),
        ),
    ]
