# Generated by Django 5.0.6 on 2026-09-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0024_alter_fopmaster_card_master_ledger'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('mailing_name', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('country', models.CharField(default='India', max_length=100)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('financial_year_from', models.DateField(blank=True, null=True)),
                ('books_beginning_from', models.DateField(blank=True, null=True)),
                ('gst_reg_type', models.CharField(choices=[('Regular', 'Regular'), ('Composition', 'Composition'), ('Unregistered', 'Unregistered'), ('SEZ', 'SEZ')], default='Regular', max_length=20)),
                ('gst_no', models.CharField(blank=True, max_length=15, null=True)),
                ('cin_number', models.CharField(blank=True, max_length=25, null=True)),
                ('tan_number', models.CharField(blank=True, max_length=15, null=True)),
                ('hsn_sac', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'CompanyMaster',
            },
        ),
        migrations.AddConstraint(
            model_name='companymaster',
            constraint=models.UniqueConstraint(fields=('company_name',), name='uq_company_master_name'),
        ),
    ]
