# Generated by Django 5.0.6 on 2026-09-22 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0025_companymaster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companymaster',
            name='is_active',
        ),
    ]
