# Generated by Django 5.0.6 on 2026-09-22 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0026_remove_companymaster_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgmaster',
            name='pg_charges_master_ledger',
            field=models.ForeignKey(blank=True, db_column='pg_charges_master_ledger_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pg_master_charges_rows', to='accounting.ledger'),
        ),
        migrations.AddField(
            model_name='pgmaster',
            name='pg_charges_master_ledger_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
