# Generated by Django 5.0.6 on 2026-09-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0027_pgmaster_pg_charges_master_ledger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketline',
            name='pg_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
