# Hand-written (not autogenerated) — the Voucher table used to serve two
# purposes at once: ticket-driven auto-posted JV rows AND manually created
# double-entry vouchers (voucher-entry.html), distinguished only by whether
# source_ticket was set. This splits them into two real tables:
#   - JournalVoucher (renamed from the existing "Vouchers" table) — every
#     existing row is ticket-driven (source_ticket always set on this data),
#     so this is a TRUE RENAME that preserves all existing rows exactly.
#   - Voucher (freshly created, reusing the "Vouchers" table name once it's
#     freed up by the rename above) — manual entries only, starts empty.
#
# `python manage.py makemigrations` cannot auto-detect this as a rename
# once the model also gains/loses fields in the same change (it offered
# "create JournalVoucher fresh + strip source_ticket off the old table"
# instead, which would have silently orphaned every existing ticket JV
# row) — written by hand instead to guarantee RenameModel + AlterModelTable
# (an actual SQL table rename, not a drop/recreate) run first.
#
# The index/constraint rename uses SeparateDatabaseAndState because this
# database's real index names (ix_vouchers_company_id, ix_vouchers_source_
# ticket - from the hand-written Schema.sql this DB was originally
# provisioned from) don't match what Django's own migration history
# (0002_ticket_ticketline_voucher) recorded for them
# (Vouchers_company_aabd4b_idx, Vouchers_source__74d6da_idx) - the state
# operations keep Django's history consistent, the database operations
# use the real physical names so the DROP INDEX statements actually work.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0028_ticketline_pg_charges'),
    ]

    operations = [
        # --- Step 1: rename the existing Vouchers table to JournalVoucher,
        # preserving every existing row (all of them are ticket-driven). ---
        migrations.RenameModel(old_name='Voucher', new_name='JournalVoucher'),
        migrations.AlterModelTable(name='journalvoucher', table='JournalVoucher'),

        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE [JournalVoucher] DROP CONSTRAINT [uq_voucher_company_no];",
                    reverse_sql="ALTER TABLE [JournalVoucher] ADD CONSTRAINT [uq_voucher_company_no] UNIQUE ([company_id], [voucher_no]);",
                ),
                migrations.RunSQL(
                    sql="ALTER TABLE [JournalVoucher] ADD CONSTRAINT [uq_journal_voucher_company_no] UNIQUE ([company_id], [voucher_no]);",
                    reverse_sql="ALTER TABLE [JournalVoucher] DROP CONSTRAINT [uq_journal_voucher_company_no];",
                ),
                migrations.RunSQL(
                    sql="DROP INDEX [ix_vouchers_company_id] ON [JournalVoucher];",
                    reverse_sql="CREATE INDEX [ix_vouchers_company_id] ON [JournalVoucher] ([company_id]);",
                ),
                migrations.RunSQL(
                    sql="DROP INDEX [ix_vouchers_source_ticket] ON [JournalVoucher];",
                    reverse_sql="CREATE INDEX [ix_vouchers_source_ticket] ON [JournalVoucher] ([source_ticket_id]);",
                ),
                migrations.RunSQL(
                    sql="CREATE INDEX [journal_voucher_company_idx] ON [JournalVoucher] ([company_id]);",
                    reverse_sql="DROP INDEX [journal_voucher_company_idx] ON [JournalVoucher];",
                ),
                migrations.RunSQL(
                    sql="CREATE INDEX [journal_voucher_ticket_idx] ON [JournalVoucher] ([source_ticket_id]);",
                    reverse_sql="DROP INDEX [journal_voucher_ticket_idx] ON [JournalVoucher];",
                ),
            ],
            state_operations=[
                migrations.RemoveConstraint(model_name='journalvoucher', name='uq_voucher_company_no'),
                migrations.AddConstraint(
                    model_name='journalvoucher',
                    constraint=models.UniqueConstraint(fields=['company_id', 'voucher_no'], name='uq_journal_voucher_company_no'),
                ),
                migrations.RemoveIndex(model_name='journalvoucher', name='Vouchers_company_aabd4b_idx'),
                migrations.RemoveIndex(model_name='journalvoucher', name='Vouchers_source__74d6da_idx'),
                migrations.AddIndex(
                    model_name='journalvoucher',
                    index=models.Index(fields=['company_id'], name='journal_voucher_company_idx'),
                ),
                migrations.AddIndex(
                    model_name='journalvoucher',
                    index=models.Index(fields=['source_ticket'], name='journal_voucher_ticket_idx'),
                ),
            ],
        ),

        migrations.AlterField(
            model_name='journalvoucher', name='voucher_type',
            field=models.CharField(default='Tax Invoice', max_length=20),
        ),
        migrations.AlterField(
            model_name='journalvoucher', name='category',
            field=models.CharField(default='AIRLINE', max_length=20),
        ),

        # --- Step 2: create a brand-new, empty Voucher table (manual
        # entries only, no source_ticket field) - reuses the "Vouchers"
        # table name now that step 1 moved the old data out of it. ---
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_id', models.IntegerField()),
                ('branch_name', models.CharField(blank=True, max_length=100, null=True)),
                ('voucher_type', models.CharField(choices=[
                    ('Journal', 'Journal'), ('Contra', 'Contra'), ('Payment', 'Payment'),
                    ('Receipt', 'Receipt'), ('Debit Note', 'Debit Note'), ('Credit Note', 'Credit Note'),
                ], default='Journal', max_length=20)),
                ('voucher_date', models.DateField()),
                ('narration', models.CharField(blank=True, max_length=250, null=True)),
                ('category', models.CharField(default='MANUAL', max_length=20)),
                ('voucher_no', models.CharField(blank=True, max_length=20, null=True)),
                ('total_debit', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('total_credit', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('lines_json', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Vouchers',
            },
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['company_id'], name='voucher_company_idx'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.UniqueConstraint(fields=['company_id', 'voucher_no'], name='uq_voucher_company_no'),
        ),
    ]
