# Generated by Django 5.2.5 on 2026-09-24 08:16
#
# Rewritten to use idempotent raw SQL (IF NOT EXISTS) for the AddField and
# CreateModel steps: an earlier deploy attempt against TiDB got partway
# through this migration (adding PGMaster.pg_charges_percentage) before
# failing on a later step, and since Django only records a migration as
# applied after every one of its operations succeeds, django_migrations
# never got a row for 0030 - so the next deploy retried AddField from
# scratch and hit "Duplicate column name" against TiDB, which doesn't roll
# back DDL from a failed migration the way a transactional schema change
# would. IF NOT EXISTS makes every operation here safe to retry no matter
# how far a previous attempt got.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0029_split_voucher_journalvoucher'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='pgmaster',
                    name='pg_charges_percentage',
                    field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    # Plain "ADD COLUMN IF NOT EXISTS" isn't supported on
                    # every MySQL version this app might run against - a
                    # DATABASE()+information_schema check via PREPARE/EXECUTE
                    # is the portable way to make this retry-safe on both
                    # MySQL and TiDB.
                    sql=[
                        "SET @col_exists := (SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'PGMaster' AND column_name = 'pg_charges_percentage');",
                        "SET @ddl := IF(@col_exists = 0, 'ALTER TABLE `PGMaster` ADD COLUMN `pg_charges_percentage` numeric(5, 2) NULL', 'SELECT 1');",
                        "PREPARE stmt FROM @ddl;",
                        "EXECUTE stmt;",
                        "DEALLOCATE PREPARE stmt;",
                    ],
                    reverse_sql=[
                        "SET @col_exists := (SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'PGMaster' AND column_name = 'pg_charges_percentage');",
                        "SET @ddl := IF(@col_exists > 0, 'ALTER TABLE `PGMaster` DROP COLUMN `pg_charges_percentage`', 'SELECT 1');",
                        "PREPARE stmt FROM @ddl;",
                        "EXECUTE stmt;",
                        "DEALLOCATE PREPARE stmt;",
                    ],
                ),
            ],
        ),
        migrations.AlterField(
            model_name='ticket',
            name='invoice_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='VoucherType',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('company_id', models.IntegerField()),
                        ('name', models.CharField(max_length=100)),
                        ('alias_name', models.CharField(blank=True, max_length=100, null=True)),
                        ('voucher_category', models.CharField(choices=[('General', 'General'), ('Journal', 'Journal'), ('Payment', 'Payment'), ('Receipt', 'Receipt'), ('Debit Note', 'Debit Note'), ('Credit Note', 'Credit Note')], default='General', max_length=20)),
                        ('is_active', models.BooleanField(default=True)),
                        ('number_method', models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual'), ('Automatic & Manual Override', 'Automatic & Manual Override')], default='Automatic', max_length=30)),
                        ('allow_additional_numbering', models.BooleanField(default=False)),
                        ('allow_effective_dates', models.BooleanField(default=False)),
                        ('allow_zero_value_transaction', models.BooleanField(default=False)),
                        ('allow_narration', models.BooleanField(default=True)),
                        ('allow_narration_in_each_ledger', models.BooleanField(default=False)),
                        ('an_width_of_invoice_number', models.IntegerField(blank=True, null=True)),
                        ('an_prefill_with_zero', models.BooleanField(default=False)),
                        ('an_restart_applicable_from', models.DateField(blank=True, null=True)),
                        ('an_restart_starting_number', models.IntegerField(blank=True, null=True)),
                        ('an_restart_period', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly'), ('None', 'None')], default='None', max_length=10)),
                        ('an_prefix_details', models.CharField(blank=True, max_length=20, null=True)),
                        ('an_suffix_details', models.CharField(blank=True, max_length=20, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        'db_table': 'VoucherType',
                        'indexes': [models.Index(fields=['company_id'], name='voucher_type_company_idx')],
                        'constraints': [models.UniqueConstraint(fields=('company_id', 'name'), name='uq_voucher_type_company_name')],
                    },
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE TABLE IF NOT EXISTS `VoucherType` (
                            `id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY,
                            `company_id` integer NOT NULL,
                            `name` varchar(100) NOT NULL,
                            `alias_name` varchar(100) NULL,
                            `voucher_category` varchar(20) NOT NULL,
                            `is_active` bool NOT NULL,
                            `number_method` varchar(30) NOT NULL,
                            `allow_additional_numbering` bool NOT NULL,
                            `allow_effective_dates` bool NOT NULL,
                            `allow_zero_value_transaction` bool NOT NULL,
                            `allow_narration` bool NOT NULL,
                            `allow_narration_in_each_ledger` bool NOT NULL,
                            `an_width_of_invoice_number` integer NULL,
                            `an_prefill_with_zero` bool NOT NULL,
                            `an_restart_applicable_from` date NULL,
                            `an_restart_starting_number` integer NULL,
                            `an_restart_period` varchar(10) NOT NULL,
                            `an_prefix_details` varchar(20) NULL,
                            `an_suffix_details` varchar(20) NULL,
                            `created_at` datetime(6) NOT NULL,
                            `updated_at` datetime(6) NOT NULL,
                            UNIQUE `uq_voucher_type_company_name` (`company_id`, `name`),
                            INDEX `voucher_type_company_idx` (`company_id`)
                        );
                    """,
                    reverse_sql="DROP TABLE IF EXISTS `VoucherType`;",
                ),
            ],
        ),
    ]
