# Generated by Django 5.2.5 on 2026-09-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0029_split_voucher_journalvoucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgmaster',
            name='pg_charges_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='invoice_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='VoucherType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('alias_name', models.CharField(blank=True, max_length=100, null=True)),
                ('voucher_category', models.CharField(choices=[('General', 'General'), ('Journal', 'Journal'), ('Payment', 'Payment'), ('Receipt', 'Receipt'), ('Debit Note', 'Debit Note'), ('Credit Note', 'Credit Note')], default='General', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('number_method', models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual'), ('Automatic & Manual Override', 'Automatic & Manual Override')], default='Automatic', max_length=30)),
                ('allow_additional_numbering', models.BooleanField(default=False)),
                ('allow_effective_dates', models.BooleanField(default=False)),
                ('allow_zero_value_transaction', models.BooleanField(default=False)),
                ('allow_narration', models.BooleanField(default=True)),
                ('allow_narration_in_each_ledger', models.BooleanField(default=False)),
                ('an_width_of_invoice_number', models.IntegerField(blank=True, null=True)),
                ('an_prefill_with_zero', models.BooleanField(default=False)),
                ('an_restart_applicable_from', models.DateField(blank=True, null=True)),
                ('an_restart_starting_number', models.IntegerField(blank=True, null=True)),
                ('an_restart_period', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly'), ('None', 'None')], default='None', max_length=10)),
                ('an_prefix_details', models.CharField(blank=True, max_length=20, null=True)),
                ('an_suffix_details', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'VoucherType',
                'indexes': [models.Index(fields=['company_id'], name='voucher_type_company_idx')],
                'constraints': [models.UniqueConstraint(fields=('company_id', 'name'), name='uq_voucher_type_company_name')],
            },
        ),
    ]
