# Generated by Django 5.2.5 on 2026-09-24 11:06
#
# Written with the same idempotent-retry pattern as migration 0030 (see its
# own comment for why): each ADD COLUMN is guarded by an information_schema
# check + PREPARE/EXECUTE, so a deploy that fails partway through this
# migration can be safely retried from scratch without hitting "Duplicate
# column name" on whatever already got added.

from django.db import migrations, models


def _add_column_if_missing_sql(column, ddl):
    return [
        f"SET @col_exists := (SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'Ledgers' AND column_name = '{column}');",
        f"SET @ddl := IF(@col_exists = 0, '{ddl}', 'SELECT 1');",
        "PREPARE stmt FROM @ddl;",
        "EXECUTE stmt;",
        "DEALLOCATE PREPARE stmt;",
    ]


def _drop_column_if_present_sql(column):
    return [
        f"SET @col_exists := (SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'Ledgers' AND column_name = '{column}');",
        f"SET @ddl := IF(@col_exists > 0, 'ALTER TABLE `Ledgers` DROP COLUMN `{column}`', 'SELECT 1');",
        "PREPARE stmt FROM @ddl;",
        "EXECUTE stmt;",
        "DEALLOCATE PREPARE stmt;",
    ]


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0030_pgmaster_pg_charges_percentage_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='ledger',
                    name='credit_days',
                    field=models.IntegerField(blank=True, default=0, null=True),
                ),
                migrations.AddField(
                    model_name='ledger',
                    name='credit_limit',
                    field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True),
                ),
                migrations.AddField(
                    model_name='ledger',
                    name='customer_type',
                    field=models.CharField(blank=True, choices=[('RETAIL', 'Retail'), ('CORPORATE', 'Corporate'), ('AGENT', 'Agent')], max_length=20, null=True),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=_add_column_if_missing_sql("credit_days", "ALTER TABLE `Ledgers` ADD COLUMN `credit_days` integer NULL DEFAULT 0"),
                    reverse_sql=_drop_column_if_present_sql("credit_days"),
                ),
                migrations.RunSQL(
                    sql=_add_column_if_missing_sql("credit_limit", "ALTER TABLE `Ledgers` ADD COLUMN `credit_limit` numeric(14, 2) NULL DEFAULT 0"),
                    reverse_sql=_drop_column_if_present_sql("credit_limit"),
                ),
                migrations.RunSQL(
                    sql=_add_column_if_missing_sql("customer_type", "ALTER TABLE `Ledgers` ADD COLUMN `customer_type` varchar(20) NULL"),
                    reverse_sql=_drop_column_if_present_sql("customer_type"),
                ),
            ],
        ),
    ]
