# Generated by Django 5.2.5 on 2026-09-29 04:36
#
# Every schema step here is wrapped in IfNeeded, which only runs the real
# operation's DDL when the database doesn't already match (column
# present/absent, table present/absent - checked via Django's own
# introspection) - same reason 0030 was rewritten: TiDB doesn't roll back
# DDL from a migration that fails partway, and Django only records a
# migration as applied once ALL its operations succeed, so a plain
# AddField retried after a partial deploy dies on "Duplicate column name"
# and blocks every future deploy. Migration state is exactly what
# makemigrations generated - IfNeeded delegates state changes unchanged.

import django.db.models.deletion
from django.db import migrations, models
from django.db.migrations.operations.base import Operation


class IfNeeded(Operation):
    reduces_to_sql = False
    reversible = True

    def __init__(self, inner):
        self.inner = inner

    def state_forwards(self, app_label, state):
        self.inner.state_forwards(app_label, state)

    def _table_columns(self, schema_editor, table):
        conn = schema_editor.connection
        with conn.cursor() as cursor:
            # Case-insensitive: MySQL on Windows (lower_case_table_names=1)
            # reports "companymaster" for db_table "CompanyMaster".
            if table.lower() not in {t.lower() for t in conn.introspection.table_names(cursor)}:
                return None
            return {c.name.lower() for c in conn.introspection.get_table_description(cursor, table)}

    def _applied(self, app_label, schema_editor, state):
        """Whether the database already reflects self.inner having run (checked against the post-operation state)."""
        op = self.inner
        if isinstance(op, migrations.CreateModel):
            model = state.apps.get_model(app_label, op.name)
            return self._table_columns(schema_editor, model._meta.db_table) is not None
        model = state.apps.get_model(app_label, op.model_name)
        columns = self._table_columns(schema_editor, model._meta.db_table) or set()
        if isinstance(op, migrations.AddField):
            return model._meta.get_field(op.name).column.lower() in columns
        if isinstance(op, migrations.RemoveField):
            return model._meta.get_field(op.name).column.lower() not in columns
        raise TypeError(f"IfNeeded doesn't support {type(op).__name__}")

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        # RemoveField's model no longer has the field in to_state, so check it against from_state's table instead.
        check_state = from_state if isinstance(self.inner, migrations.RemoveField) else to_state
        if not self._applied(app_label, schema_editor, check_state):
            self.inner.database_forwards(app_label, schema_editor, from_state, to_state)

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        check_state = to_state if isinstance(self.inner, migrations.RemoveField) else from_state
        if self._applied(app_label, schema_editor, check_state):
            self.inner.database_backwards(app_label, schema_editor, from_state, to_state)

    def describe(self):
        return f"{self.inner.describe()} (if not already applied)"


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0031_ledger_credit_days_ledger_credit_limit_and_more'),
    ]

    operations = [
        IfNeeded(migrations.RemoveField(
            model_name='companymaster',
            name='description',
        )),
        IfNeeded(migrations.AddField(
            model_name='companymaster',
            name='currency_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        )),
        IfNeeded(migrations.AddField(
            model_name='companymaster',
            name='currency_symbol',
            field=models.CharField(blank=True, max_length=5, null=True),
        )),
        IfNeeded(migrations.AddField(
            model_name='companymaster',
            name='decimal_places',
            field=models.PositiveSmallIntegerField(blank=True, default=2, null=True),
        )),
        IfNeeded(migrations.AddField(
            model_name='companymaster',
            name='logo_base64',
            field=models.TextField(blank=True, null=True),
        )),
        IfNeeded(migrations.AddField(
            model_name='companymaster',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        )),
        IfNeeded(migrations.AddField(
            model_name='companymaster',
            name='seal_base64',
            field=models.TextField(blank=True, null=True),
        )),
        IfNeeded(migrations.AddField(
            model_name='pgmaster',
            name='pg_charges_percentage_effective_from',
            field=models.DateField(blank=True, null=True),
        )),
        IfNeeded(migrations.AddField(
            model_name='ticketline',
            name='pg_charges_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        )),
        IfNeeded(migrations.CreateModel(
            name='PGMasterHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField()),
                ('gateway_name', models.CharField(max_length=100)),
                ('payment_master_ledger_id', models.IntegerField(blank=True, null=True)),
                ('payment_master_ledger_name', models.CharField(blank=True, max_length=200, null=True)),
                ('pg_charges_master_ledger_id', models.IntegerField(blank=True, null=True)),
                ('pg_charges_master_ledger_name', models.CharField(blank=True, max_length=200, null=True)),
                ('pg_charges_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('effective_from', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pg_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='accounting.pgmaster')),
            ],
            options={
                'db_table': 'PGMasterHistory',
                'ordering': ['-effective_from'],
                'indexes': [models.Index(fields=['pg_master', 'effective_from'], name='PGMasterHis_pg_mast_94f575_idx')],
                'constraints': [models.UniqueConstraint(fields=('pg_master', 'effective_from'), name='uq_pg_master_history_effective_from')],
            },
        )),
    ]
