# Generated by Django 5.2.5 on 2026-09-30 05:31
#
# Every step is wrapped in IfNeeded, which runs the real operation's DDL
# only when the database doesn't already match (column/table/index/
# constraint present or absent, via Django's introspection) - TiDB doesn't
# roll back DDL from a migration that fails partway, so an unguarded step
# retried after a partial deploy would fail and block every later deploy.
# Same approach as 0032. Migration state is exactly what makemigrations
# generated - IfNeeded delegates state changes unchanged.

import django.db.models.deletion
from django.db import migrations, models
from django.db.migrations.operations.base import Operation


class IfNeeded(Operation):
    reduces_to_sql = False
    reversible = True

    def __init__(self, inner):
        self.inner = inner

    def state_forwards(self, app_label, state):
        self.inner.state_forwards(app_label, state)

    @staticmethod
    def _table(schema_editor, table):
        """(columns, constraint/index names) of `table`, lower-cased; None if the table is missing."""
        conn = schema_editor.connection
        with conn.cursor() as cursor:
            if table.lower() not in {t.lower() for t in conn.introspection.table_names(cursor)}:
                return None
            columns = {c.name.lower() for c in conn.introspection.get_table_description(cursor, table)}
            names = {n.lower() for n in conn.introspection.get_constraints(cursor, table)}
        return columns, names

    def _applied(self, app_label, schema_editor, state):
        """Whether the database already reflects self.inner having run (checked against the post-operation state)."""
        op = self.inner
        if isinstance(op, migrations.CreateModel):
            model = state.apps.get_model(app_label, op.name)
            return self._table(schema_editor, model._meta.db_table) is not None
        model = state.apps.get_model(app_label, op.model_name)
        found = self._table(schema_editor, model._meta.db_table)
        columns, names = found or (set(), set())
        if isinstance(op, migrations.AddField):
            return model._meta.get_field(op.name).column.lower() in columns
        if isinstance(op, migrations.RemoveField):
            return model._meta.get_field(op.name).column.lower() not in columns
        if isinstance(op, migrations.AddIndex):
            return op.index.name.lower() in names
        if isinstance(op, migrations.AddConstraint):
            return op.constraint.name.lower() in names
        raise TypeError(f"IfNeeded doesn't support {type(op).__name__}")

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        # RemoveField's model no longer has the field in to_state, so check it against from_state's table instead.
        check_state = from_state if isinstance(self.inner, migrations.RemoveField) else to_state
        if not self._applied(app_label, schema_editor, check_state):
            self.inner.database_forwards(app_label, schema_editor, from_state, to_state)

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        check_state = to_state if isinstance(self.inner, migrations.RemoveField) else from_state
        if self._applied(app_label, schema_editor, check_state):
            self.inner.database_backwards(app_label, schema_editor, from_state, to_state)

    def describe(self):
        return f"{self.inner.describe()} (if not already applied)"


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0032_pgmaster_history_company_master_fields'),
    ]

    operations = [
        IfNeeded(migrations.RemoveField(
            model_name='vouchertype',
            name='allow_narration_in_each_ledger',
        )),
        IfNeeded(migrations.RemoveField(
            model_name='vouchertype',
            name='allow_zero_value_transaction',
        )),
        IfNeeded(migrations.CreateModel(
            name='RescheduleAirlineTicket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_id', models.IntegerField()),
                ('branch_name', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_number', models.CharField(max_length=20)),
                ('invoice_date', models.DateField()),
                ('invoice_type', models.CharField(blank=True, max_length=100, null=True)),
                ('booking_mode', models.CharField(choices=[('Manual', 'Manual'), ('Auto Push', 'Auto Push')], default='Manual', max_length=20)),
                ('booking_type', models.CharField(blank=True, max_length=30, null=True)),
                ('booking_status', models.CharField(blank=True, choices=[('Confirmed', 'Confirmed'), ('Re-Scheduled', 'Re-Scheduled')], max_length=20, null=True)),
                ('travel_type', models.CharField(blank=True, choices=[('Domestic', 'Domestic'), ('International', 'International')], max_length=20, null=True)),
                ('user_name', models.CharField(blank=True, max_length=100, null=True)),
                ('currency', models.CharField(default='INR', max_length=5)),
                ('roe', models.DecimalField(decimal_places=4, default=1, max_digits=10)),
                ('booking_given_by', models.CharField(blank=True, max_length=25, null=True)),
                ('booking_reference', models.CharField(max_length=30)),
                ('booking_ref_date', models.DateField(blank=True, null=True)),
                ('airline_pnr', models.CharField(blank=True, max_length=13, null=True)),
                ('gds_pnr', models.CharField(blank=True, max_length=13, null=True)),
                ('office_id', models.CharField(blank=True, max_length=30, null=True)),
                ('payment_mode', models.CharField(blank=True, choices=[('Top-up', 'Top-up'), ('Payment Gateway', 'Payment Gateway')], max_length=20, null=True)),
                ('payment_gateway_ref', models.CharField(blank=True, max_length=60, null=True)),
                ('airline_category', models.CharField(blank=True, choices=[('LCC', 'LCC'), ('FSC', 'FSC'), ('OSC', 'OSC')], max_length=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(db_column='customer_ledger_id', on_delete=django.db.models.deletion.PROTECT, related_name='reschedules_as_customer', to='accounting.ledger')),
                ('original_ticket', models.ForeignKey(db_column='original_ticket_id', on_delete=django.db.models.deletion.PROTECT, related_name='reschedules', to='accounting.ticket')),
                ('supplier', models.ForeignKey(blank=True, db_column='supplier_ledger_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reschedules_as_supplier', to='accounting.ledger')),
            ],
            options={
                'db_table': 'RescheduleAirlineTickets',
            },
        )),
        IfNeeded(migrations.CreateModel(
            name='RescheduleAirlineTicketLine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('airline_code', models.CharField(blank=True, max_length=200, null=True)),
                ('airline_name', models.CharField(blank=True, max_length=200, null=True)),
                ('airline_category', models.CharField(blank=True, choices=[('LCC', 'LCC'), ('FSC', 'FSC'), ('OSC', 'OSC')], max_length=5, null=True)),
                ('flight_no', models.CharField(blank=True, max_length=200, null=True)),
                ('ticket_no', models.CharField(max_length=30)),
                ('passenger_name', models.CharField(max_length=50)),
                ('pax_type', models.CharField(choices=[('Adult', 'Adult'), ('Child', 'Child'), ('Infant', 'Infant')], default='Adult', max_length=10)),
                ('sector', models.CharField(blank=True, max_length=200, null=True)),
                ('travel_date', models.CharField(blank=True, max_length=200, null=True)),
                ('cabin', models.CharField(blank=True, max_length=200, null=True)),
                ('travel_class', models.CharField(blank=True, max_length=200, null=True)),
                ('fare_type', models.CharField(blank=True, max_length=300, null=True)),
                ('basic_fare', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('yq', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('yr', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('k3_tax', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_others', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('seat', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('meal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('baggage', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('other_ssr', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('disc_on', models.CharField(blank=True, max_length=20, null=True)),
                ('disc_type', models.CharField(blank=True, choices=[('Percentage', 'Percentage'), ('Flat', 'Flat')], max_length=12, null=True)),
                ('disc_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tds_per', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('pg_charges', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('pg_charges_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('markup', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('addl_markup', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('ssr_markup', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('service_fee', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('addl_service_fee', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('ssr_service_fee', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gst_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('supp_comm_on', models.CharField(blank=True, max_length=20, null=True)),
                ('supp_comm_type', models.CharField(blank=True, choices=[('Percentage', 'Percentage'), ('Flat', 'Flat')], max_length=12, null=True)),
                ('supp_comm_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('supp_tds_per', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('supp_markup', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('supp_addl_markup', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('supp_service_fee', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('supp_addl_service_fee', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('supp_gst_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('agent_penalty', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('supplier_penalty', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_billed', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('ISSUED', 'Issued'), ('REFUNDED', 'Refunded'), ('VOID', 'Void'), ('EXCHANGED', 'Exchanged')], default='ISSUED', max_length=15)),
                ('office_id', models.CharField(blank=True, max_length=30, null=True)),
                ('fop', models.CharField(blank=True, choices=[('Own Card', 'Own Card'), ('Client Card', 'Client Card'), ('Cash', 'Cash')], max_length=20, null=True)),
                ('card_number', models.CharField(blank=True, max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_ticket_line', models.ForeignKey(db_column='original_ticket_line_id', on_delete=django.db.models.deletion.PROTECT, related_name='reschedule_lines', to='accounting.ticketline')),
                ('reschedule_ticket', models.ForeignKey(db_column='reschedule_ticket_id', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.rescheduleairlineticket')),
                ('supplier', models.ForeignKey(blank=True, db_column='supplier_ledger_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reschedulelines_as_supplier', to='accounting.ledger')),
            ],
            options={
                'db_table': 'RescheduleAirlineTicketLines',
            },
        )),
        IfNeeded(migrations.AddIndex(
            model_name='rescheduleairlineticket',
            index=models.Index(fields=['company_id'], name='RescheduleA_company_33ccf0_idx'),
        )),
        IfNeeded(migrations.AddIndex(
            model_name='rescheduleairlineticket',
            index=models.Index(fields=['original_ticket'], name='RescheduleA_origina_53e2da_idx'),
        )),
        IfNeeded(migrations.AddConstraint(
            model_name='rescheduleairlineticket',
            constraint=models.UniqueConstraint(fields=('company_id', 'invoice_number'), name='uq_resched_ticket_company_invoice_no'),
        )),
        IfNeeded(migrations.AddConstraint(
            model_name='rescheduleairlineticket',
            constraint=models.UniqueConstraint(fields=('company_id', 'booking_reference'), name='uq_resched_ticket_company_booking_ref'),
        )),
        IfNeeded(migrations.AddIndex(
            model_name='rescheduleairlineticketline',
            index=models.Index(fields=['reschedule_ticket'], name='RescheduleA_resched_4fdae7_idx'),
        )),
        IfNeeded(migrations.AddIndex(
            model_name='rescheduleairlineticketline',
            index=models.Index(fields=['original_ticket_line'], name='RescheduleA_origina_075131_idx'),
        )),
        IfNeeded(migrations.AddConstraint(
            model_name='rescheduleairlineticketline',
            constraint=models.UniqueConstraint(fields=('ticket_no',), name='uq_resched_ticketline_ticket_no'),
        )),
    ]
