# Generated by Django on 2026-10-10, guarded for TiDB / MySQL

from django.db import migrations


def safe_rename_indexes(apps, schema_editor):
    conn = schema_editor.connection
    q = schema_editor.quote_name
    with conn.cursor() as cursor:
        for table, old, new in [
            ("AL_Tickets", "Tickets_company_e95274_idx", "AL_Tickets_company_023cd9_idx"),
            ("AL_TicketLines", "TicketLines_ticket__ba671e_idx", "AL_TicketLi_ticket__4dce9f_idx"),
        ]:
            try:
                constraints = {n.lower() for n in conn.introspection.get_constraints(cursor, table)}
                if old.lower() in constraints and new.lower() not in constraints:
                    cursor.execute(f"ALTER TABLE {q(table)} RENAME INDEX {q(old)} TO {q(new)}")
            except Exception:
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0037_appuser_menumaster_usermenuaccess_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameIndex(
                    model_name='ticket',
                    new_name='AL_Tickets_company_023cd9_idx',
                    old_name='Tickets_company_e95274_idx',
                ),
                migrations.RenameIndex(
                    model_name='ticketline',
                    new_name='AL_TicketLi_ticket__4dce9f_idx',
                    old_name='TicketLines_ticket__ba671e_idx',
                ),
            ],
            database_operations=[
                migrations.RunPython(safe_rename_indexes, migrations.RunPython.noop),
            ],
        ),
    ]
